services:
  prowlarr:
    image: ghcr.io/hotio/prowlarr:release
    container_name: prowlarr
    restart: ${RESTART_POLICY}
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - UMASK=${UMASK}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${CONFIG_PATH}/prowlarr:/config
    ports:
      - 9696:9696

  sonarr:
    image: ghcr.io/hotio/sonarr:release
    container_name: sonarr
    restart: ${RESTART_POLICY}
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - UMASK=${UMASK}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${CONFIG_PATH}/sonarr:/config
      - ${DATA_PATH}:/data
    ports:
      - 8989:8989

  radarr:
    image: ghcr.io/hotio/radarr:release
    container_name: radarr
    restart: ${RESTART_POLICY}
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - UMASK=${UMASK}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${CONFIG_PATH}/radarr:/config
      - ${DATA_PATH}:/data
    ports:
      - 7878:7878

  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd:latest
    container_name: sabnzbd
    restart: ${RESTART_POLICY}
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
      - UMASK=${UMASK}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${CONFIG_PATH}/sabnzbd:/config
      - ${DATA_PATH}/usenet:/data/usenet
    ports:
      - 8080:8080

  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    restart: unless-stopped
    network_mode: host
    devices:
     - /dev/dri:/dev/dri # QuickSync
    volumes:
      - ${CONFIG_PATH}/plex:/config
      - ${DATA_PATH}:/data

  recyclarr:
    image: ghcr.io/recyclarr/recyclarr
    container_name: recyclarr
    user: 1000:1000
    environment:
      - TZ=${TZ}
    volumes:
      - ${CONFIG_PATH}/recyclarr:/config

  pulsarr:
    image: lakker/pulsarr:latest
    container_name: pulsarr
    ports:
      - 3003:3003
    volumes:
      - ${CONFIG_PATH}/pulsarr:/app/data
      - /docker/servarr/.env:/app/.env
    restart: unless-stopped
    environment:
      - TZ=${TZ}
      - baseUrl=http://pulsarr

  whisparr:
    container_name: whisparr
    image: ghcr.io/hotio/whisparr
    ports:
      - 6969:6969
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
      - UMASK=${UMASK}
      - WEBUI_PORTS=6969/tcp
    volumes:
      - ${CONFIG_PATH}/whisparr:/config
      - ${DATA_PATH}:/data

  stash:
    image: stashapp/stash:latest
    container_name: stash
    restart: unless-stopped
    # ports:
    #   - 9999:9999
    network_mode: host
    environment:
      - STASH_STASH=/data/
      - STASH_GENERATED=/generated/
      - STASH_METADATA=/metadata/
      - STASH_CACHE=/cache/
      - STASH_PORT=9999
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${CONFIG_PATH}/stash/metadata:/metadata
      - ${CONFIG_PATH}/stash/cache:/cache
      - ${CONFIG_PATH}/stash/blobs:/blobs
      - ${CONFIG_PATH}/stash/generated:/generated
      - ${CONFIG_PATH}/stash/config:/root/.stash
      - ${DATA_PATH}:/data
    # logging:
    #   driver: "json-file"
    #   options:
    #     max-file: "10"
    #     max-size: "2m"